apiVersion: v1
kind: Service
metadata:
  name: test11
  namespace: namespace-workflow-1683220029275
spec:
  type: LoadBalancer
  selector:
    app: test11
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80